#!/usr/bin/env bash
#A script that prints all current running processes including those which might not hava TTY. displayed in a user-oriented format, in an hierarchical manner.
ps -axu | grep bash | tail -n 1
