#!/usr/bin/env bash
#a Bash script that displays numbers from 1 to 100.
#Requirements:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

for each in {1..100}
do
	if [ $((each % 3)) -eq 0 ]
	then
		if [ $((each % 5)) -eq 0 ]
		then
			echo "FizzBuzz"
		else 
			echo "Fizz"
		fi
	elif [ $((each % 5)) -eq 0 ]  && [ $((each % 3)) -ne 0 ]
	then
		echo "Buzz"
	else
		echo "$each"
	fi
done
