#!/usr/bin/env bash

#Write a Bash script that displays the time for 12 hours and 59 minutes:
#	-display hours from 0 to 12
#	-display minutes from 1 to 59
#Requirements:
#	-You must use the while loop (for and until are forbidden

Hour=1
Minutes=1
while [ $Hour -ne 14 ]
do 
	echo "$Minutes"
	((Minutes++))	
	if [ $Minutes -eq 60 ]  
	then
		if [ $Hour -ne 13 ]
		then
		echo "Hour: $Hour"
		fi

		Minutes=1
		((Hour++))
	fi
	
done
